import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";
import { componentTagger } from "lovable-tagger";
import { execSync } from "child_process";
import { readFileSync, writeFileSync } from "fs";

const BUILD_INFO_PATH = path.resolve(__dirname, "src/build-info.ts");
const REPO_URL = "https://github.com/dfar-io/pkmnforge";

// Try to resolve the current commit SHA. Lovable's build environment shadows
// the `git` binary, so prefer `__LOVABLE_REAL_GIT` when present. Returns null
// if no real SHA is available — caller should fall back to existing source.
const tryResolveCommitSha = (): string | null => {
  const gitBin = process.env.__LOVABLE_REAL_GIT || "git";
  try {
    const sha = execSync(`${gitBin} rev-parse HEAD`, {
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
    if (sha) return sha;
  } catch {
    /* fall through */
  }
  return (
    process.env.VERCEL_GIT_COMMIT_SHA ||
    process.env.COMMIT_REF ||
    process.env.GITHUB_SHA ||
    null
  );
};

// Read the previously-baked SHA from src/build-info.ts so the published build
// (where git is unreachable) still has a real commit hash to display.
const readBakedSha = (): string => {
  try {
    const src = readFileSync(BUILD_INFO_PATH, "utf8");
    const m = src.match(/BUILD_COMMIT\s*=\s*"([^"]+)"/);
    return m?.[1] ?? "dev";
  } catch {
    return "dev";
  }
};

// Regenerate src/build-info.ts when we have a real SHA. The file is committed
// to source so its value survives into environments where git isn't available.
const refreshBuildInfo = (): { commit: string; builtAt: string } => {
  const live = tryResolveCommitSha();
  const baked = readBakedSha();
  const commit = live ?? baked;
  const builtAt = new Date().toISOString();

  // Only rewrite when we actually obtained a fresh SHA — avoid clobbering the
  // baked value with "dev" in environments without git access.
  if (live) {
    const contents = `// AUTO-GENERATED by vite.config.ts on every dev/build run.
// Committed to source so the published build has a real commit SHA even when
// the publish environment lacks git access. Do not edit by hand.
export const BUILD_COMMIT: string = "${live}";
export const BUILD_TIME: string = "${builtAt}";
export const REPO_URL: string = "${REPO_URL}";
`;
    try {
      const existing = readFileSync(BUILD_INFO_PATH, "utf8");
      if (existing !== contents) writeFileSync(BUILD_INFO_PATH, contents);
    } catch {
      writeFileSync(BUILD_INFO_PATH, contents);
    }
  }

  return { commit, builtAt };
};

const { commit: COMMIT_SHA, builtAt: BUILD_TIME } = refreshBuildInfo();

// Emit /version.json into the build output. UpdateNotifier polls this to
// detect new deploys without hashing index.html.
const versionJsonPlugin = (): Plugin => ({
  name: "emit-version-json",
  apply: "build",
  generateBundle() {
    this.emitFile({
      type: "asset",
      fileName: "version.json",
      source: JSON.stringify({ commit: COMMIT_SHA, builtAt: BUILD_TIME }, null, 2),
    });
  },
});

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  server: {
    host: "::",
    port: 8080,
    hmr: {
      overlay: false,
    },
  },
  plugins: [
    react(),
    mode === "development" && componentTagger(),
    versionJsonPlugin(),
  ].filter(Boolean),
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
    dedupe: ["react", "react-dom", "react/jsx-runtime", "react/jsx-dev-runtime", "@tanstack/react-query", "@tanstack/query-core"],
  },
}));
