// AUTO-GENERATED by vite.config.ts on every dev/build run.
// Committed to source so the published build has a real commit SHA even when
// the publish environment lacks git access. Do not edit by hand.
export const BUILD_COMMIT: string = "b050945f4ade8e52b5570f892e3156b78bdc56e9";
export const BUILD_TIME: string = "2026-04-19T16:55:19.357Z";
export const REPO_URL: string = "https://github.com/dfar-io/pkmnforge";
