// AUTO-GENERATED by vite.config.ts on every dev/build run.
// Committed to source so the published build has a real commit SHA even when
// the publish environment lacks git access. Do not edit by hand.
export const BUILD_COMMIT: string = "1c1793cb11513907a6aec4b140fdef6e3c65318d";
export const BUILD_TIME: string = "2026-04-24T17:17:48.887Z";
export const REPO_URL: string = "https://github.com/dfar-io/pkmnforge";
