// AUTO-GENERATED by vite.config.ts on every dev/build run.
// Committed to source so the published build has a real commit SHA even when
// the publish environment lacks git access. Do not edit by hand.
export const BUILD_COMMIT = "a4da41514e13bdb95e2b4e6d64ffbdde31de0af4";
export const BUILD_TIME = "2026-04-18T19:31:09.770Z";
export const REPO_URL = "https://github.com/dfar-io/pkmnforge";
